name: build Ardour for macOS
on: [push]
jobs:
  download-dependency-sources:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2

      - name: Cache sources
        uses: actions/cache@v2
        with:
          path: ./dependency_sources
          key: dependency_sources

      - name: Download sources
        run: |
          mkdir -p dependency_sources
          cd dependency_sources
          ../download_dependency_sources.sh

  build-dependencies:
    needs: download-dependency-sources
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve source cache
        uses: actions/cache@v2
        with:
          path: ./dependency_sources
          key: dependency_sources

      - name: Cache dependency builds
        uses: actions/cache@v2
        with:
          path: ./build_dependencies
          key: build_dependencies

      - name: Build dependencies
        run: |
          mkdir -p build_dependencies
          cd build_dependencies
          ../build_dependencies.sh
